spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/muebles
    username: quartzone
    password: quartzone
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
