DROP TABLE MUEBLE;
DROP TABLE ALMACEN;
DROP TABLE STOCK;

CREATE TABLE MUEBLE(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
)

CREATE TABLE ALMACEN(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
)

CREATE TABLE STOCK(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idMueble BIGINT NOT NULL,
    idAlmacen BIGINT NOT NULL,
    maxStock INTEGER NOT NULL,
    minStock INTEGER NOT NULL,
    actualStock INTEGER NOT NULL,
    CONSTRAINT fk_mueble FOREIGN KEY (idMueble) REFERENCES MUEBLE(id) ON DELETE CASCADE,
    CONSTRAINT fk_almacen FOREIGN KEY (idAlmacen) REFERENCES ALMACEN(id) ON DELETE CASCADE    
)
